FROM ubuntu
RUN apt-get update \
    && apt-get install -y iputils-ping \
    && apt-get install -y iproute2 \
    && apt install net-tools \
    && apt-get install -y python3

#CMD ip addr add 10.0.0.2/24 dev eth0