#docker run --privileged -it
FROM ubuntu
RUN apt-get update \
&& apt-get install -y iputils-ping \
&& apt-get install -y iproute2 \
&& apt install net-tools \
&& apt-get install -y python3

#CMD ip link add eth1 type dummy \
#&& ip link set eth1 up 
#&& ip addr add 192.168.0.254/24 dev eth0 \
#&& ip addr add 10.0.0.254/24 dev eth1



