FROM ubuntu:22.04

COPY init-victime-script.sh /init-victime-script.sh
COPY script/main_victime.py /main_victime.py 
COPY script/data.txt /data.txt
COPY script/data1.txt /data1.txt
COPY victime_exe /victime_exe 
RUN apt-get update \
    && apt-get install -y iputils-ping \
    && apt-get install -y iproute2 \
    && apt install net-tools \
    && apt-get install nano -y \
    && apt-get install -y python3 python3-pip libpcap-dev \
    && pip3 install scapy \
    && chmod +x /init-victime-script.sh \
    && chmod +x /main_victime.py \
    && chmod +x /data.txt \
    && chmod +x /data1.txt \
    && chmod +x /victime_exe 




