#docker run --privileged -it
FROM ubuntu
RUN apt-get update \
&& apt-get install -y iputils-ping \
&& apt-get install -y iproute2 \
&& apt install net-tools \
&& apt-get install -y python3 python3-pip libpcap-dev \
&& pip3 install scapy




