FROM ubuntu

COPY init-firewall-script.sh /path/inside/container/init-firewall-script.sh
RUN apt-get update \
&& apt-get install -y iputils-ping \
&& apt-get install -y iproute2 \
&& apt-get install -y iptables \
&& apt install net-tools \
&& apt-get install -y python3 python3-pip libpcap-dev \
&& pip3 install scapy \
&& chmod +x /path/inside/container/init-firewall-script.sh




