FROM ubuntu:22.04

COPY init-hacker-script.sh /init-hacker-script.sh
COPY script/main_attacker.py /main_attacker.py 
COPY main_attacker /attacker_exe 
RUN apt-get update \
    && apt-get install -y iputils-ping \
    && apt-get install -y iproute2 \
    && apt install net-tools \
    && apt-get install nano -y \
    && apt-get install -y python3 python3-pip libpcap-dev \
    && pip3 install scapy \
    && chmod +x /init-hacker-script.sh \
    && chmod +x /main_attacker.py \
    && chmod +x /attacker_exe  \