version: "3"

services:
  victime:
    build:
      context: .
      dockerfile: Dockerfile_victime
    stdin_open: true
    privileged: true
    tty: true
    networks: 
      PAN :
        ipv4_address: 10.10.10.2
    command: ["/path/inside/container/init-victime-script.sh"]

  hacker:
    build:
      context: .
      dockerfile: Dockerfile_Hacker
    stdin_open: true
    privileged: true
    tty: true
    networks: 
      WAN:
        ipv4_address: 192.168.10.2
    command: ["/path/inside/container/init-hacker-script.sh"]

  firewall:
    build:
      context: .
      dockerfile: Dockerfile_Firewall
    stdin_open: true
    privileged: true
    tty: true 
    networks:
      PAN:
        ipv4_address: 10.10.10.254
      WAN:
        ipv4_address: 192.168.10.254
    restart: unless-stopped
    command: ["/path/inside/container/init-firewall-script.sh"]

networks:
  PAN:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          ip_range: 10.10.10.0/24
  WAN:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.0/24

